name    = Dist-Zilla-PluginBundle-MIKKOI
author  = Mikko Koivunalho <mikkoi@cpan.org>
license = Perl_5
copyright_holder = Mikko Koivunalho
copyright_year   = 2023

[@Filter]
-bundle  = @Basic
-remove  = License
-remove  = ExtraTests
-version = 5.031

[OurPkgVersion]
[Git::NextVersion]
[NextRelease]
[@Git]
[MetaJSON]
[AutoPrereqs]

[Prereqs / RuntimeRequires]
; perl = 5.014
Dist::Zilla::Plugin::MetaJSON = 0
Dist::Zilla::Plugin::PodWeaver = 0
Dist::Zilla::Plugin::PerlTidy = 0
Dist::Zilla::Plugin::PruneFiles = 0
Dist::Zilla::Plugin::MinimumPerl = 0
Dist::Zilla::Plugin::AutoPrereqs = 0
Dist::Zilla::Plugin::Test::PodSpelling = 0
Dist::Zilla::Plugin::Test::DistManifest = 0
Dist::Zilla::Plugin::MetaTests = 0
Dist::Zilla::Plugin::PodSyntaxTests = 0
Dist::Zilla::Plugin::PodCoverageTests = 0
Dist::Zilla::Plugin::Test::Portability = 0
Dist::Zilla::Plugin::Test::Version = 0
Dist::Zilla::Plugin::Test::Kwalitee = 0
Dist::Zilla::Plugin::Test::CPAN::Changes = 0
Dist::Zilla::Plugin::Test::Perl::Critic = 0
Dist::Zilla::Plugin::Test::EOL = 0
Dist::Zilla::Plugin::Test::UnusedVars = 0
Dist::Zilla::Plugin::Test::Synopsis = 0
Dist::Zilla::Plugin::Test::Pod::LinkCheck = 0
Dist::Zilla::Plugin::RunExtraTests = 0
Dist::Zilla::Plugin::Test::CPAN::Meta::JSON = 0
Dist::Zilla::Plugin::Test::MinimumVersion = 0
Dist::Zilla::Plugin::MojibakeTests = 0
Dist::Zilla::Plugin::Test::NoTabs = 0
Dist::Zilla::Plugin::Signature = 0
Dist::Zilla::Plugin::AuthorSignatureTest = 0
Dist::Zilla::Plugin::Test::Software::Policies = 0
